version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.4
    working_directory:
    steps:
      - checkout
      - python/install-packages:
        pkg-manager: pip
      - run:
          name: Tests
          command: pytest
      - run:
          name: Linting
          command: flake8

workflows:
  build-and-test:
    jobs: build-and-test
